### ISSUE TITLE
https://github.com/linkedin/css-blocks/tree/master/packages/@css-blocks/website is not working

### ISSUE THREAD

**Issue by jordiviva** [linkedin/css-blocks#166]
I tried to download the boilerplate of cs-blocks with create-react-app of your github repository in https://github.com/linkedin/css-blocks/tree/master/packages/@css-blocks/website , I did the npm install and npm start, and the code is not running, npm run build is not working as well.

/Users/kuroneko/Desktop/css-blocks/css-blocks/packages/@css-blocks/website/scripts/start.js:11
  throw err;
  ^

Error: [css-blocks] ImportError: Error parsing block import "./Home.block.css". Failed with:

"Object.entries is not a function"

 (/Users/kuroneko/Desktop/css-blocks/css-blocks/packages/@css-blocks/website/src/pages/Home/index.tsx:8)
    at CssBlockError (/Users/kuroneko/Desktop/css-blocks/css-blocks/packages/@css-blocks/website/node_modules/@css-blocks/jsx/dist/src/utils/Errors.js:9:9)
    at TemplateImportError (/Users/kuroneko/Desktop/css-blocks/css-blocks/packages/@css-blocks/website/node_modules/@css-blocks/jsx/dist/src/utils/Errors.js:57:9)
    at ImportDeclaration.analyzer.blockFactory.getBlockFromPath.catch (/Users/kuroneko/Desktop/css-blocks/css-blocks/packages/@css-blocks/website/node_modules/@css-blocks/jsx/dist/src/Analyzer/visitors/importer.js:96:27)

**Comment by jordiviva** [comment]
node v.8.9.4

![image](https://user-images.githubusercontent.com/6263700/39672027-1d443664-5123-11e8-8593-5d54590a3ef5.png)

**Comment by amiller-gh** [comment]
Hm, looks like Object static entries is only supported in Node `>=8.10`: http://kangax.github.io/compat-table/es2016plus/

We should provide a polyfill for `Object.entries`, or refactor to use a different method.

**Comment by jordiviva** [comment]
I tryed again, and I think the problem is a Warning I'm getting:

WARNING: Stray reference to block import (styles). Imports are removed during rewrite so this will probably be a runtime error. 

So as it says, on runtime I'm having errors of Uncaught ReferenceError: styles is not defined
Seems like the sintax of 
`import styles from './button.block.css';
`
is not working.

**Comment by chriseppstein** [comment]
@jordiviva Did you change the code in any way?  Perhaps by adding a `console.log(styles)`? The styles that we import do not actually have a runtime representation like they would in css-modules/style-loader. It is just syntax that we analyze and transform into templates that know how to access the optimized CSS that is expected to be loaded into the browser's runtime scope. Obviously, this project works for us, because we build and deploy the website. I noticed you're on windows, perhaps there's some issue with our code on that platform. It would be great if you could try to investigate and find the root cause. If not, maybe try using another starter-project for css blocks like this one: https://github.com/matthiaskern/css-blocks-hello-world

**Comment by jordiviva** [comment]
Ok, since you ensure that It works, I tried to reinstall the project on Mac, with node 8.1 and going by the instructions of getting started and finally I could execute the code satisfactorily, so let's try it on a real project now ^^.

I don't know why it didn't work with windows, maybe it's because windows don't support the NODE_ENVIRONMENT variable, so I had to delete the conditional of it from the project to execute it.

**Comment by chriseppstein** [comment]
@jordiviva ok. we should def figure out why it didn't work on windows, then. It's not super high priority for us at the moment. Once you get a handle on things, if you have some cycles to debug it, that would be really helpful.
